package ie.joe.statemachine.domain;

public enum OrderState {
  OPENED
  , IN_PROGRESS
  , PROCESSING_ORDER_FORK
  , PROCESSING_ORDER
  , PROCESSING_ORDER_JOIN
  , AWAIT_FILLING
  , READY_FOR_SHIPMENT
  , SENT_TO_DISPATCH
  , READY_FOR_INVOICE
  , AWAITING_PAYMENT
  , PAYMENT_RECEIVED
  , AWAITING_DISPATCH_APPROVAL
  , COMPLETE
}
